name: dev

on:
  push:
    branches:
      - weidian

env:
  TZ: Asia/Shanghai

jobs:
  mac-package:
    runs-on: macos-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install dependencies
        run: |
          npm run build:graphql-docs
          npm run build:bruno-query
          npm run build:bruno-common
          npm run build:web

      - name: Build Electron app
        run: npm run build:electron:mac

      - name: List build
        run: ls -la packages/bruno-electron/out

      - uses: actions/upload-artifact@v4
        with:
          name: build-macos
          path: |
            ./packages/bruno-electron/out/bruno_*
          retention-days: 1
          if-no-files-found: error
